{{ config(materialized='table') }}

SELECT
    GAME_ID, --string
    SEASON,
    SEASON_TYPE,
    TEAM_ID,
    TEAM_LOCATION AS TEAM_LOC,
    TEAM_NAME,
    TEAM_ABBREVIATION AS TEAM_ABBREV,
    TEAM_HOME_AWAY,
    OPPONENT_TEAM_ID AS OPP_TEAM_ID,
    OPPONENT_TEAM_LOCATION AS OPP_TEAM_NAME,
    OPPONENT_TEAM_NAME AS OPP_TEAM_MASCOT,
    OPPONENT_TEAM_ABBREVIATION AS OPP_TEAM_ABBREV,
    FAST_BREAK_POINTS AS FAST_BREAK_PTS,
    POINTS_IN_PAINT AS PTS_IN_PAINT,
    TURNOVER_POINTS AS TURNOVER_PTS,
    LARGEST_LEAD,
    CAST(GAME_DATE AS DATE) AS GAME_DATE,
    CAST(GAME_DATE_TIME AS DATETIME) AS GAME_DATE_TIME,
    CAST(TEAM_SCORE AS INT64) AS TEAM_SCORE,
    CAST(TEAM_WINNER AS BOOLEAN) AS TEAM_WINNER,
    CAST(ASSISTS AS INT64) AS ASSISTS,
    CAST(BLOCKS AS INT64) AS BLOCKS,
    CAST(DEFENSIVE_REBOUNDS AS INT64) AS DEF_REBOUNDS,
    CAST(FIELD_GOAL_PCT AS FLOAT64) AS FIELD_GOAL_PCT,
    CAST(FIELD_GOALS_MADE AS INT64) AS FIELD_GOALS_MADE,
    CAST(FIELD_GOALS_ATTEMPTED AS INT64) AS FIELD_GOALS_ATT,
    CAST(FLAGRANT_FOULS AS INT64) AS FLAGR_FOULS,
    CAST(FOULS AS INT64) AS FOULS,
    CAST(FREE_THROW_PCT AS FLOAT64) AS FREE_THROW_PCT,
    CAST(FREE_THROWS_MADE AS INT64) AS FREE_THROWS_MADE,
    CAST(FREE_THROWS_ATTEMPTED AS INT64) AS FREE_THROWS_ATT,
    CAST(OFFENSIVE_REBOUNDS AS INT64) AS OFF_REBOUNDS,
    CAST(STEALS AS INT64) AS STEALS,
    CAST(TEAM_TURNOVERS AS INT64) AS TEAM_TURNOVERS,
    CAST(TECHNICAL_FOULS AS INT64) AS TECH_FOULS,
    CAST(THREE_POINT_FIELD_GOAL_PCT AS FLOAT64)
        AS THREE_PT_FIELD_GOAL_PCT,
    CAST(THREE_POINT_FIELD_GOALS_MADE AS INT64) AS THREE_PT_FIELD_GOALS_MADE,
    CAST(THREE_POINT_FIELD_GOALS_ATTEMPTED AS INT64)
        AS THREE_PT_FIELD_GOALS_ATT,
    CAST(TOTAL_REBOUNDS AS INT64) AS TOT_REBOUNDS,
    CAST(TOTAL_TECHNICAL_FOULS AS INT64) AS TOT_TECH_FOULS,
    CAST(TOTAL_TURNOVERS AS INT64) AS TOT_TURNOVERS,
    CAST(TURNOVERS AS INT64) AS TURNOVERS,
    CAST(OPPONENT_TEAM_SCORE AS INT64) AS OPP_TEAM_SCORE
FROM
    {{ source('team_23_project', 'wnba-teambox-2019-2024') }}
ORDER BY
    GAME_DATE, GAME_ID, TEAM_HOME_AWAY
